version: "3.9"

services:
    app:
        image: ghcr.io/darmshot/shopper:${IMAGE_TAG:-latest}
        restart: unless-stopped
        ports:
            - "127.0.0.1:${APP_PORT:-80}:8000"
        env_file:
            - .env
        networks:
            - shopper
        depends_on:
            - mysql
            - redis
    mysql:
        image: percona/percona-server:8.0
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS:-}"
        volumes:
            - shopper-mysql:/var/lib/mysql
        networks:
            - shopper
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        volumes:
            - 'shopper-redis:/data'
        networks:
            - shopper
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

networks:
    shopper:
        driver: bridge

volumes:
    shopper-mysql:
    shopper-redis:

