name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST_PRODUCTION }}
          username: ${{ vars.SSH_USER_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          script: |
            set -ex
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}:sha-${{ env.SHORT_SHA }}

            cd ${{ vars.DEPLOY_PATH_PRODUCTION }}

            # Run migrations
            IMAGE_TAG=sha-${{ env.SHORT_SHA }} docker compose -f production.compose.yaml run --rm cli php artisan migrate --force

            # Deploy new image
            IMAGE_TAG=sha-${{ env.SHORT_SHA }} docker compose -f production.compose.yaml up -d --force-recreate

            docker system prune -f
